### PR TITLE
Allow a custom quality value when using NeuQuant

### PR DESCRIPTION
**Pull request by rukai**
When generating a lot of gifs its crucial to be able to generate them faster but with lower quality.

Maybe we should do `let nq = color_quant::NeuQuant::new(31 - quality, 256, pixels);`
So that quality becomes a value in the range [0, 30] that INCREASES the quality?

### CODE REVIEW

**Comment by HeroicKatora** [comment]
Would it make sense to keep the old interface as calling the new one with the default value that it currently supplies? I have no knowledge about the specifics of NeuQuant though.

**Comment by rukai** [comment]
I need this for a project I am working on, so my plan was to make this breaking change and then release image-gif 0.11
I dont think we should be worried about breaking the api before a 1.0.0 release.
And I think its nicer to just have one function.

If you think the API would be better with double the functions, then we can do that instead.

Can't say I have any particular experience with NeuQuant myself, I'm just reading the docs for the new method here https://docs.rs/color_quant/1.0.1/color_quant/struct.NeuQuant.html#method.new

**Comment by HeroicKatora** [comment]
Major version bump also means that an update is required to [every dependent crate](https://crates.io/crates/gif/reverse_dependencies). Those don't technically require a major version bump if their own stable interface is not affected but what's the chance of that? Consider that `rustc` treats traits from different majors versions of the same crate as incompatble etc.

Yeah, several projects have been quite liberal with major versions but it seems not very costly to prevent it in this case. Should the constructor methods get out of hand we can always deprecate and remove them in the future.

**Comment by rukai** [comment]
"Should the constructor methods get out of hand we can always deprecate and remove them in the future."
But then we will end up with a function named: `from_rgba_quality` when a better api would just name it `from_rgba`.

**Comment by HeroicKatora** [comment]
I had the impression that the opposite was the case. Since it took so long for the extra parameter to be necessary the default seems sensible and usable (and `from_rgba` sounds like a decently commonly used method). Less parameters are obviously less complex and since none of us both, who have already looked at the implementation, know exactly what the paramter is tuning I doubt it would give an ergonomic expression if it were the default. 

Should that turn out to be wrong, what I'm saying is that deprecating and reworking the 'simply named' interface is as much a breaking change as changing the parameters is now. But I'd delay that since I don't see the quality parameter control being a major motiviation for most usages. Furthermore, the choice of how to rework then need not be committed to now. For example a builder style for default parameter could be a viable alternative to complicated functions names? Or maybe the method should really be on the instance of `NeuQuant`. Note that `NeuQuant::new` is a considerable portion of the runtime cost and hence that way might provide valuable runtime gains for batch processing of images.

**Comment by rukai** [comment]
Hey, those are some good points, I have changed it to a separate function.

I've also changed the variable name from `quality` to `speed`. The reasons being:
*   People will reach for this function when they want its too slow and they want to speed it up.
*   Its more intuitive, as the number going up means more speed.

**Pull request merged**
