### PR TITLE
Make color_quant optional

### PR DESCRIPTION
**Pull request by kornelski**
I'm using pngquant, so I don't need to use another crate. Quantization is also unnecessary when using this crate to only decode gifs.

### CODE REVIEW

**Comment by HeroicKatora** [comment]
Is there a significant benefit for removing the crate from the dependency graph? It doesn't come with transitive dependencies of its own nor native code and is 100% safe.

**Comment by kornelski** [comment]
It's always one crate less to compile.

**Review by fintelia — APPROVED** [review]
I'm not sure how much of a difference in compile time this will actually have, but it seems fine

**Review by HeroicKatora — COMMENTED** [review]
Okay, but we should test the additional feature combinations. Add them here, please: https://github.com/image-rs/image-gif/blob/master/.github/workflows/rust.yml#L13

**Review by HeroicKatora — APPROVED** [review]

**Pull request merged**
