### PR TITLE
Adding benchmark.

### PR DESCRIPTION
**Pull request by adetaylor**
This benchmark approach is based on similar code for the
jpeg-decoder crate.

### CODE REVIEW

**Comment by JohnTitor** [comment]
I think it'd be nice to run benchmark on CI like jpeg-decoder.

**Comment by HeroicKatora** [comment]
What would running benchmarks on CI achieve? It's the least reproducible environment I can think of. The code would run

a) on virtual machines
b) with arbitrary other running code
c) with arbitrary other parallel machines
c) utilizing an uncontrollable portion of resources
c) of unknown (and changing) virtual hardware
d) on unknown (and changing) real hardware

For `jpeg-decoders` the usefulness is questionable. For example, jobs [337.7](https://travis-ci.org/image-rs/jpeg-decoder/jobs/625359098) and [334.7](https://travis-ci.org/image-rs/jpeg-decoder/jobs/623214638) are after and before a performance improvement PR. However, performance as read from the log has *decreased* by quite a lot. I'm somewhat confident that you'll not be able to reproduce this directly on any single piece of hardware.

**Comment by JohnTitor** [comment]
@HeroicKatora Fair enough, thanks for clarifying. As you said, it seems no achievement from running a benchmark on CI. Sorry for the wrong suggestion!

**Comment by HeroicKatora** [comment]
Since you asked in the other PR, no Rust major version bump can be made in a minor version. This can nevertheless be accepted in a new major version. If you can demonstrate some significant performance gains that you found using the benchmark, I personally think that would motivate a new major version.

**Comment by HeroicKatora** [comment]
Thanks a lot, I've rebased them and integrated in #73

**Pull request closed without merging**
